#!/bin/bash

c=/opt/msys/ecelerity/bin/ec_console

header() {
  echo -e "\n$1:\n" >> $log
  echo "[Getting $1]"
}

export TZ="UTC"
filename_date_str=$(date +"%Y%m%d-%H-%M-%S-UTC")

mkdir -p $HOME/snap_logs
log="$HOME/snap_logs/snap-${filename_date_str}.log"
touch $log

symlink="$HOME/snap_logs/latest.log"
ln -s -f $log $symlink

echo "Logging to $symlink"

header "hostname"
hostname -f >> $log

header "time"
date +'%s' >> $log
export TZ="UTC"
date >> $log
export TZ="America/New_York"
date >> $log

header "memory"
free -b | perl -0 -ne 'if (/Mem:\s+(\d+).+buffers\/cache:\s+(\d+)\s+(\d+)/s) { my $c = 1024**3; my $pct_free = ($3/$1)*100.0; printf("capacity: %.1f GB\nused: %.2f GB (%.1f%)\nfree: %.1f GB (%.1f%)\n", $1/$c, $2/$c, ($2/$1)*100.0, $3/$c, ($3/$1)*100.0); }' >> $log

header "top by memory"
top -a -b -n1 | head -30 >> $log

header "disk"
df -h >> $log

#header "iostat"
#iostat -cdxt 2 2 >> $log

#header "mpstat"
#mpstat -P ALL 2 2 >> $log

#header "sar"
#sar >> $log

header "paniclog"
tail -50 /var/log/ecelerity/paniclog.ec >> $log

header "httplog"
tail -50 /var/log/ecelerity/httplog.ec >> $log

#header "/var/log/messages"
#sudo tail -50 /var/log/messages >> $log

#header "version"
#echo "version" | sudo -u ecuser $c >> $log

#header "summary"
#echo "summary" | sudo -u ecuser $c >> $log

header "threads stats"
echo "threads stats" | sudo -u ecuser $c >> $log

header "scriptlet threads stats"
echo "scriptlet threads stats" | sudo -u ecuser $c >> $log

header "ecelerity memory"
echo "memory" | sudo -u ecuser $c >> $log

if [[ $1 == "gstack" ]]; then
  header "gstack"
  sudo /opt/msys/ecelerity/bin/gstack_ecelerity -q >> $log
fi

echo "" >> $log
echo "snap complete" >> $log
echo "snap complete"
echo "see $symlink"
